import ModulesStateBasic from 'kts-scaffold-framework/modules/ModulesStateBasic';
import { IInvoiceDetails } from 'src/api/invoiceInput/querySingleDetail/IData';

/** 模块状态 */
export default class ModulesState extends ModulesStateBasic {
    invoiceDetails: IInvoiceDetails = {
        acceptTaxName: 'string',
        acceptTaxNum: 'string',
        amount: 2,
        amountTax: 2,
        amountWithoutTax: 2,
        blueInvoiceCode: 'string',
        blueInvoiceNo: 'string',
        buyerAddressPhone: 'string',
        buyerBankAndId: 'string',
        buyerIdNum: 'string',
        buyerName: 'string',
        buyerTaxId: 'string',
        cancellationMark: 'string',
        carrierTaxName: 'string',
        carrierTaxNum: 'string',
        certificate: 'string',
        certificateImport: 'string',
        checkCount: 'string',
        cid: 'string',
        currentTaxPeriod: 'string',
        drawer: 'string',
        engineNo: 'string',
        factoryModel: 'string',
        incomeInvoiceBizId: 2,
        inspectionNum: 'string',
        invoiceCode: 'string',
        invoiceDate: 1522412026000,
        invoiceId: 'string',
        invoiceNumber: 'string',
        invoiceParityCode: 'string',
        invoiceStatus: 'string',
        invoiceType: 'string',
        legalizeDate: 'string',
        legalizeEndDate: 'string',
        legalizeInvoiceDateBegin: 'string',
        legalizeInvoiceDateEnd: 'string',
        legalizeState: 'string',
        limitPeople: 'string',
        machineCode: 'string',
        payee: 'string',
        productPlace: 'string',
        receiveName: 'string',
        receiveTaxNum: 'string',
        remark: 'string',
        reviewer: 'string',
        saleItemList: [],
        salerBankAccount: 'string',
        salerPhone: 'string',
        shipperName: 'string',
        shipperTaxNum: 'string',
        supplierAddressPhone: 'string',
        supplierBankAndId: 'string',
        supplierName: 'string',
        supplierTaxId: 'string',
        taxBureauCode: 'string',
        taxBureauName: 'string',
        taxDiskNumber: 'string',
        taxRate: 'string',
        taxRecords: 'string',
        tonnage: 'string',
        trafficFeeFlag: 'string',
        transportInfo: 'string',
        vehicleNo: 'string',
        vehicleNum: 'string',
        vehicleTonnage: 'string',
        vehicleType: 'string',
        wayInfo: 'string',
        zeroTaxRateFlag: 'string',
    };
    lastRealCheckTime: number = 1522412026000;
}